import Link from "next/link";
import { ArrowRight, BarChart3, Brush, Check, ClipboardList, Paintbrush, Users } from "lucide-react";

const features = [
  { icon: ClipboardList, title: "Tekliften teslimata", text: "Her duvar boyama işini teklif, hazırlık, uygulama ve teslim adımlarıyla takip edin." },
  { icon: Users, title: "Ustalarınızı organize edin", text: "Ekipte kimin hangi adreste, hangi işte ve hangi tarihte olduğunu net görün." },
  { icon: BarChart3, title: "İşletmenizi ölçün", text: "Gelir, tamamlanan işler ve yoğun dönemleri sade raporlarla izleyin." },
];

export default function Home() {
  return (
    <main className="min-h-screen bg-[#f4f8fc] text-[#18324b]">
      <nav className="sticky top-0 z-20 border-b border-[#dce8f3] bg-white/95 backdrop-blur-md"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-10"><Link href="/" className="flex items-center gap-3 font-semibold tracking-tight"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#2571c5] text-white"><Paintbrush size={19} /></span><span className="text-lg">PaintCo<span className="text-[#2571c5]">.</span></span></Link><div className="flex items-center gap-4"><span className="hidden text-xs font-semibold uppercase tracking-[0.18em] text-[#18324b]/40 sm:inline">Duvar boyama yönetimi</span><Link href="/admin/login" className="inline-flex items-center gap-2 rounded-lg bg-[#2571c5] px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-[#1d5fa8]">Yönetici girişi <ArrowRight size={15} /></Link></div></div></nav>
      <section className="relative overflow-hidden border-b border-[#dce8f3] bg-white"><div className="absolute right-0 top-0 h-full w-1/3 bg-[#e3f1ff]" /><div className="relative mx-auto grid max-w-7xl gap-16 px-6 py-24 lg:grid-cols-[1.1fr_0.9fr] lg:px-10 lg:py-32"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#b9d8f3] bg-[#f0f7ff] px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.17em] text-[#2571c5]"><Brush size={14} /> Boya ustaları için</div><h1 className="max-w-4xl text-5xl font-semibold leading-[1.02] tracking-[-0.06em] text-[#18324b] sm:text-7xl">Duvar boyama işinizi <span className="text-[#2571c5]">daha iyi yönetin.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#18324b]/60">Müşteri tekliflerinden ekip planına, oda hazırlığından son rötuşlara kadar boya işinizin tamamı tek, anlaşılır bir panelde.</p><div className="mt-10 flex flex-wrap items-center gap-4"><Link href="/admin/login" className="inline-flex items-center gap-2 rounded-lg bg-[#2571c5] px-6 py-3.5 font-semibold text-white transition hover:bg-[#1d5fa8]">Paneli aç <ArrowRight size={17} /></Link><a href="#ozellikler" className="rounded-lg border border-[#b9d8f3] px-6 py-3.5 font-semibold text-[#2571c5] transition hover:bg-[#f0f7ff]">Neler sunuyor?</a></div></div><div className="relative flex items-end"><div className="w-full rounded-2xl border border-[#b9d8f3] bg-[#f4f8fc] p-6 shadow-[0_18px_45px_rgba(37,113,197,0.1)]"><div className="flex items-center justify-between border-b border-[#dce8f3] pb-5"><div><p className="text-xs font-semibold uppercase tracking-[0.17em] text-[#2571c5]">Bugünkü işler</p><p className="mt-1 text-2xl font-semibold">Sahada netlik</p></div><span className="rounded-full bg-[#dff4e8] px-3 py-1 text-xs font-semibold text-[#27754c]">Aktif</span></div><div className="space-y-3 pt-5">{["Salon · Kadıköy", "Dış cephe · Üsküdar", "Ofis · Ataşehir"].map((job, index) => <div key={job} className="flex items-center gap-3 rounded-xl border border-[#dce8f3] bg-white p-3"><span className={`h-2.5 w-2.5 rounded-full ${index === 1 ? "bg-[#f0b34a]" : "bg-[#3ca56d]"}`} /><span className="text-sm font-medium">{job}</span><span className="ml-auto text-xs text-[#18324b]/40">{index === 0 ? "Hazırlık" : index === 1 ? "Uygulama" : "Teslim"}</span></div>)}</div></div></div></div></section>
      <section id="ozellikler" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-[#2571c5]">Boya işiniz için</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">Her işin rengi, tarihi ve sorumlusu belli.</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-2xl border border-[#dce8f3] bg-white p-7 shadow-[0_8px_24px_rgba(37,113,197,0.05)]"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#e3f1ff] text-[#2571c5]"><Icon size={21} /></div><h3 className="mt-7 text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-[#18324b]/60">{text}</p></article>)}</div></section>
      <section className="mx-6 mb-10 overflow-hidden rounded-2xl bg-[#2571c5] text-white lg:mx-auto lg:max-w-7xl"><div className="grid gap-10 px-8 py-12 sm:px-14 sm:py-16 md:grid-cols-[1fr_auto] md:items-end"><div><Check className="text-[#a8dcff]" size={27} /><h2 className="mt-5 max-w-xl text-3xl font-semibold tracking-[-0.05em] sm:text-4xl">Daha düzenli işler, daha güçlü bir boya işletmesi.</h2><p className="mt-4 max-w-lg leading-7 text-white/75">PaintCo, günlük saha işini ve yönetim tarafını aynı yerde tutmak isteyen duvar boyama ekipleri için hazırlandı.</p></div><Link href="/admin/login" className="inline-flex items-center justify-center gap-2 rounded-lg bg-white px-6 py-3.5 font-semibold text-[#2571c5] transition hover:bg-[#e3f1ff]">Yönetici girişi <ArrowRight size={17} /></Link></div></section>
      <footer className="mx-auto flex max-w-7xl flex-col gap-3 px-6 py-8 text-sm text-[#18324b]/50 sm:flex-row sm:items-center sm:justify-between lg:px-10"><span>© 2026 PaintCo</span><span>Duvar boyama işiniz için sade yönetim</span></footer>
    </main>
  );
}
